
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 13 02:03:32 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 23;
  public static final int READ = 26;
  public static final int IDENT = 15;
  public static final int PLUS = 25;
  public static final int RBRACE = 4;
  public static final int RPAREN = 13;
  public static final int EQUAL = 6;
  public static final int CHARS = 16;
  public static final int SEMI = 7;
  public static final int RETURN = 28;
  public static final int LBRACKET = 9;
  public static final int LPAREN = 12;
  public static final int LBRACE = 3;
  public static final int RBRACKET = 10;
  public static final int INC = 18;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int DIV = 22;
  public static final int PROG = 2;
  public static final int DEC = 19;
  public static final int MINUS = 20;
  public static final int PRINT = 27;
  public static final int CONST = 5;
  public static final int error = 1;
  public static final int NEW = 24;
  public static final int BOOL = 17;
  public static final int MUL = 21;
  public static final int VOID = 11;
}

